---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitops-init-license
spec:
  params:
    - name: cluster_name
      type: string
    - name: account
      type: string
    - name: secrets_path
      type: string
    - name: mas_instance_id
      type: string
  stepTemplate:
    name: gitops-init-license
    env:
      - name: CLUSTER_NAME
        value: $(params.cluster_name)
      - name: ACCOUNT
        value: $(params.account)
      - name: SECRET_PATH
        value: $(params.secrets_path)
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
  steps:
    - args:
      - |-
        mascli/mas gitops-init-license -a $ACCOUNT -c $CLUSTER_NAME -m $MAS_INSTANCE_ID \
        --secrets-path $SECRET_PATH \
        --license-file /workspace/license/entitlement.lic
      command:
        - /bin/sh
        - -c
      name: gitops-init-license
      imagePullPolicy: Always
      image: quay.io/ibmmas/cli:6.1.0-pre.gitops
  workspaces:
    - name: license

